### PR TITLE
Add support for React 18

### PR DESCRIPTION
**Pull request by mmmulani**
Solves #21. Tested it locally and it works fine.

### CODE REVIEW

**Comment by fuzzthink** [comment]
Works for me too. Can we get this in?

**Comment by roryg** [comment]
Also hoping we can get this merged in!

**Comment by isTravis** [comment]
@dminkovsky Thanks for the work on this project! Any chance for a quick merge and publish of this?  

If this repo is unmaintained, could you please let us know so that someone in the community can fork it and merge in quick updates like this.

Thanks again!

**Comment by dminkovsky** [comment]
Hey I'm really sorry I missed this PR somehow! Thanks for the bump. I'll check it out and publish this evening when I have a few.

**Comment by dminkovsky** [comment]
1.3.0 should now be on npm. Thank you!

**Comment by isTravis** [comment]
Amazing - thanks so much @dminkovsky!

**Pull request merged**
